blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.PostList.as_view(), name="post_list"),
    path("detail/<int:pk>/", views.PostDetail.as_view(), name="post_detail"),
    path("comment/<int:pk>/",views.CommentCreate.as_view(),name="comment_create"),
    path("category/<int:pk>/", views.PostCategoryList.as_view(),name="post_category_list"),
    path("tag/<int:pk>/",views.PostTagList.as_view(),name="post_tag_list"),
]

myprofile/urls.py
from . import views
from django.urls import path

app_name = "myprofile"

urlpatterns = [
    path("", views.top, name ="top"),
    path("resume/", views.resume, name ="resume"),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path("diaries/", include("diaries.urls")),
    path("reviews/", include("reviews.urls")),
    path("contact/", include("contact.urls")),
    path("videos/", include("videos.urls")),
    path("blog/", include("blog.urls")),
    path("", include("myprofile.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myprofile/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
# Create your views here.
def top(request):
    context = {
        "name": "たろう",
    }
    html = loader.render_to_string("myprofile/top.html", context=context,request=request)
    return HttpResponse(html)

def resume(request):
    return render(request, "myprofile/resume.html")

myprofile/templates/myprofile/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="veiwport" content="width=device-width,initial-scale=1">
  <title>{% block title %}{% endblock %}</title>
</head>
<body>

<header>Taro's Profile</header>

<nav>
  <a href="{% url 'myprofile:top' %}">TOP</a>
  <a href="{% url 'myprofile:resume' %}">Resume</a>
</nav>


{% block content %}{% endblock %}

</body>
</html>

myprofile/templates/myprofile/resume.html
{% extends "myprofile/base.html" %}

{% block title %}Taro's Profile {% endblock %}

{% block content %}
 <h1>履歴　職務履歴</h1>

 <h2>履歴</h2>
 <table>
   <tr>
     <th>2015</th>
     <td>〇〇株式会社にて、CTOとして活躍</td>
   </tr>
 </table>

 <h2>学歴</h2>
{% endblock %}

myprofile/templates/myprofile/top.html
{% extends "myprofile/base.html" %}

{% block title %}Taro's profile{% endblock %}

{% block content %}
 <h1>{{name}}についての概要</h1>
 <p>東京に住んでいる、40歳になったエンジニアです。</p>

<h2>趣味</h2>
<ul>
  <li>映画観賞</li>
<ul>
　他の色々なコンテンツ・・・
{% endblock %}